### ISSUE TITLE
Tried to Register, Unable to enter Password

### ISSUE THREAD

**Issue by ManCalledM** [deweycd/ProjectFrontier#11]
I tried to Create a collection tool account, but was unable to make a password (Note: the password I tried to make had Letters and numbers, so it should have worked.)

**Comment by Nephalemfire23** [comment]
Having the same issue, My password is basic letters and numbers and I've even tried adding special characters and it still comes back as invalid format.

**Comment by deweycd** [comment]
I'm sorry it took so long, I was away on vacation and unable to locate the issue prior to leaving.  You should now have no issue with registering.
