### ISSUE TITLE
I can't login into my account

### ISSUE THREAD

**Issue by blazeyorozuki** [deweycd/ProjectFrontier#12]
Hello, I am Blaze, and I'm sure there is a bug in it. I can't login with passwords, even my overwrite password. I tried everything to login into the Brave Frontier Collection Set, but I was unable to. You could say it NEVER let me login. Please end this bug, because I have new units and want to add to it. If it's not a bug, then what is it?

**Comment by deweycd** [comment]
I've looked into your account and have had to reset the password to get it to work. I've sent the new account details to your email.  Let me know how it goes.
