### ISSUE TITLE
Units Not Saving

### ISSUE THREAD

**Issue by LivingLegacy** [deweycd/ProjectFrontier#3]
I added a couple of units to see how the site worked, however upon exiting the site and coming back I found that one of the units did not save. This happened the first time I had added the units and it happened again once I re-added the unit that had gone missing. I want to add more units but I don't want to put the time into it if It's just going to not save them. The units I added were Zeruiah and Avant and Avant is the one who did not save.

**Comment by deweycd** [comment]
Are you using the multi-summon or add summon option?  A recent issue with add summon has been fixed that was causing similar issues.

**Comment by LivingLegacy** [comment]
add summon. It may have been the same issue as It seems to be working now.
