### ISSUE TITLE
Editing Unit Issue

### ISSUE THREAD

**Issue by Midnightblueblade** [deweycd/ProjectFrontier#4]
When introducing changes to an existing unit (increase in level, new imps, etc.) the site creates a duplicate unit with the updated stats and does not save changes to the original.

**Comment by LivingLegacy** [comment]
Can confirm. Also having this issue.

**Comment by deweycd** [comment]
This has been repaired, it will now save to the original. It was creating a new record each edit, now it will create new only if a record does not already exist.
