### ISSUE TITLE
Disappearing Units

### ISSUE THREAD

**Issue by Midnightblueblade** [deweycd/ProjectFrontier#8]
I was looking through my sets and noticed a few units that I had entered were missing. I searched through my unit list and couldn't find them there either. These units were my 7* Elimo, 7* Signas, 7* Colt, and 7* Avant. The only thing in common that I can think of about these units is that they were all max level and either fully or partially imped.

**Comment by deweycd** [comment]
Were these units entered recently or were these entered a week or two ago? We had an issue with disappearing units that has been fixed. If you are still having this issue I need to know when they were last entered and your username.

**Comment by Midnightblueblade** [comment]
If I recall correctly they were added roughly a week ago, and they were all individually added via Add Summon, same as the person who had reported something similar earlier. So it is possible that it happened earlier and that I just didn't notice.
