### ISSUE TITLE
HP Sorting - Table Button

### ISSUE THREAD

**Issue by GustavoCinque** [deweycd/ProjectFrontier#9]
Sorting units by HP doesn't correctly sort the units

Screen shots:

Ascending:
![ascending](https://cloud.githubusercontent.com/assets/13166137/15765144/cb1e74e8-2907-11e6-995b-b3418a1adca0.jpg)

Descending:
![descending](https://cloud.githubusercontent.com/assets/13166137/15765088/02b8218e-2907-11e6-871c-e34adf573bea.jpg)

**Comment by deweycd** [comment]
I have made the appropriate changes, this will not function as intended.
